### PR TITLE
Update to scrapePostPage

### PR DESCRIPTION
**Pull request by evolross**
Updated returned JSON data reference in `scrapePostPage` to latest JSON model returned on the post page from IG.  This makes `scrapePostPage` and `deepScrapeTagPage` work correctly as of the time of this update.

### CODE REVIEW

**Comment by evolross** [comment]
I think the checks are failing because the example JSON data is old. I didn't update that. Can do that when I get a chance.

**Comment by nordhagen** [comment]
Weird. The tests were failing so I updated them and then they passed. Now they're failing again. This is what you get when scraping I guess. Will look into it.

**Comment by evolross** [comment]
The current code is still working for me... I'll paste in the latest fixtures tomorrow on my fork and see if the tests pass.

**Comment by evolross** [comment]
I finally got around to updating the fixtures. Just the `fixtures/postPage.html` actually. The tests all passed in my fork after this update.  So the post page fixture just needed updating to match the live IG site.

It looks like in your `master` the `fixtures` had not been updated (which you mention above on Aug 24 that you did - I'm assuming you meant you updated your text fixtures).

It's updated now. I've created a PR for you and the tests pass.

**Pull request merged**
